// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3A9R4ZMlkS5_Lacm2b2WQTGwjeEUeYmc',
    appId: '1:498151346914:web:485067e478f1b4018b84bb',
    messagingSenderId: '498151346914',
    projectId: 'phoneauthtest-7869a',
    authDomain: 'phoneauthtest-7869a.firebaseapp.com',
    storageBucket: 'phoneauthtest-7869a.appspot.com',
    measurementId: 'G-WBCWLY95L4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTM_YBJy4_EFLvqvi8MooKuA2elWnoMN0',
    appId: '1:498151346914:android:bdad53a8d211270c8b84bb',
    messagingSenderId: '498151346914',
    projectId: 'phoneauthtest-7869a',
    storageBucket: 'phoneauthtest-7869a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBf4bWlxLCPeynaHUxPiCEOJ1b7NBxz1YY',
    appId: '1:498151346914:ios:eb4fec9c3e5aff528b84bb',
    messagingSenderId: '498151346914',
    projectId: 'phoneauthtest-7869a',
    storageBucket: 'phoneauthtest-7869a.appspot.com',
    androidClientId: '498151346914-e6uvdpg7oh304ahmhfp79i1ir4bau45v.apps.googleusercontent.com',
    iosClientId: '498151346914-c1g6625trkb97k4mi4tliveic36a8s7c.apps.googleusercontent.com',
    iosBundleId: 'com.example.mydemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBf4bWlxLCPeynaHUxPiCEOJ1b7NBxz1YY',
    appId: '1:498151346914:ios:eb4fec9c3e5aff528b84bb',
    messagingSenderId: '498151346914',
    projectId: 'phoneauthtest-7869a',
    storageBucket: 'phoneauthtest-7869a.appspot.com',
    androidClientId: '498151346914-e6uvdpg7oh304ahmhfp79i1ir4bau45v.apps.googleusercontent.com',
    iosClientId: '498151346914-c1g6625trkb97k4mi4tliveic36a8s7c.apps.googleusercontent.com',
    iosBundleId: 'com.example.mydemo',
  );
}
